project:
  type: website

website:
  title: "How Do Position and Age Correlate With Soccer Injuries ?"
  navbar:
    left:
      - about.qmd
      - home.qmd
      - text: "Injuries"
        menu:
            - injuries.qmd
            - goalkeeper.qmd
            - defender.qmd
            - midfielder.qmd
            - forwarder.qmd
      - age.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



