project:
  type: website

website:
  title: "Injuries, Goals and Something"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Home
      - goals.qmd
      - one_more.qmd
      - conclusion.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



