---
title: "Goals"
---

```{r}
#| echo: false
#| output: false
library(tidyverse)
library(readxl)
library(plotly)
library(ggiraph)
library(gganimate)
library(dplyr)

premier_league <- read_excel("../Final-project/premier_league_data.xlsx")
```

## Goals Plot

Goals may depend on the quality or age of the player which can affect the level at which the player performs in a game

```{r}
#| echo: false
#| message: false
#| warning: false
prem_data_plot <- premier_league|>
select(full_name, age, position, Current_Club, goals_overall)|>
ggplot(mapping = aes(x = age,
                     y = goals_overall,
                     text = paste("Name:",full_name, "\n",
                                  "Team:", Current_Club, "\n",
                                  "Pos:", position, "\n",
                                  "Goals:", goals_overall, "\n"),
                     color = position)) +
geom_point()+
theme_classic()+
labs(title = "Amount of Goals Compared to Age in Premier League",
     x = "Age",
     y = "Total Goals per Player",
     caption = "Source: ill get later")
ggplotly(prem_data_plot, tooltip = "text")
```